[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
wmp_staking = "4NwpwZsSoqRQZu8EKCuG5oujwPfyMyRxZSjm7x2HXrmB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=5db8c362-82b2-485b-8479-c7070537e638"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
